[package]
name = "debugito"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
clap = "4.5.30"
gimli = "0.31"
glob = "0.3.3"
nix = {version = "0.29", features = ["ptrace"]}
object = "0.37.0"
reedline = "0.38.0"
rsprocmaps = "0.3.2"
